# -*- coding: utf-8 -*-
"""pas_notebook_auxiliar_.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19X4rnxyhkAYXORtU8HHnMLSx1-yGnSmD

# PAS - Notebook auxiliar - Análise de dado da Banda Larga

Para essa atividade você vai trabalhar com um recorte dos dados. Os dados originais foram extraídos do site [Base dos Dados](basedosdados.org/) a partir da base que possui informações de contratos da banda larga no Brasil. No recorte foram extraídos os dados de 2018 à 2022 das 26 capitais e do Distrito Federal. Os dados completos podem ser acessados [neste link](https://gist.githubusercontent.com/adolfoguimaraes/7202a4b356d485ded9e5ce9df953c936/raw/f01e392bdc9af84a501f895abfb36092505f7231/anatel_bandalarga_capitais.csv). A seguir, é mostrado como carrega-lo usando a linguagem Python com a biblioteca Pandas.
"""

import pandas as pd

data_ = pd.read_csv("https://gist.githubusercontent.com/adolfoguimaraes/7202a4b356d485ded9e5ce9df953c936/raw/f01e392bdc9af84a501f895abfb36092505f7231/anatel_bandalarga_capitais.csv")

data_.head()

print("Tamanho da base: %i linhas e %i colunas" % (data_.shape[0], data_.shape[1]))

"""### Dicas

Para fazer um recorte da base, você pode utilizar o método `query` e fazer as seleções a partir dos atributos. Por exemplo, se quiser retornar somente os dados de 2021 de Aracaju, posso utilizar o código a seguir:
"""

recorte_ = data_.query("ano == 2021 and nome_municipio == 'Aracaju'")
recorte_.head()

"""Para as visualizações, existem várias bibliotecas. O próprio pandas tem ferramentas para isso. Outra opção é utilizar a biblioteca `seaborn`. No material complementar foi indicado um notebook com algumas opções de gráficos que podem ser criados com os seus respectivos códigos. Ele pode ser acessado [neste link](https://github.com/adolfoguimaraes/datascience/blob/main/code/01_laboratorio_analise_de_dados.ipynb).

Boa atividade 😏
"""